# Dependencies
markdown:        kramdown
highlighter:     rouge
jekyll-paginate: true
# Permalinks
permalink:       pretty
gems: [jekyll-paginate]

paginate: 5
paginate_path: "page:num"

# Setup
title:            Daniel Ternyak
tagline:          'A Site About Myself'
description:      'I build web applications with Python and JavaScript on the Cloud.'
url:              http://hyde.getpoole.com

author:
  name:           'Daniel Ternyak'
  url:            https://twitter.com/dternyak
